
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    build: ./kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - "/mnt/c/Users/StepanMoc/Desktop/VSCode/TBD/cv09/kafka-stream:/files:rw"
    command: ["bash", "-c", "/etc/confluent/docker/run & /files/kafka/start-stream.sh"]

  jobmanager:
    build: ./flink
    container_name: jobmanager
    ports:
      - "8081:8081"
      - "9999:9999"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager  
    volumes:
      - "/mnt/c/Users/StepanMoc/Desktop/VSCode/TBD/cv09/kafka-stream:/files:rw"
    depends_on:
      - kafka

  taskmanager:
    build: ./flink
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 
    volumes:
      - "/mnt/c/Users/StepanMoc/Desktop/VSCode/TBD/cv09/kafka-stream:/files:rw"
